name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # This is to catch new releases of VS Code which could cause the extension to break
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read # for checkout

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 24
                
  #     - run: npm ci
  #       env:
  #         BINDL_CURRENT_ONLY: "true"
  #     - name: Test with VS Code 1.105.0
  #       uses: GabrielBB/xvfb-action@v1
  #       env:
  #         VSCODE_TEST_VERSION: "1.105.0"
  #       with:
  #         run: npm test

  build:
    # strategy:
    #   matrix:
    #     include:
    #       - os: windows-latest
    #         target: win32-x64
    #         npm_config_arch: x64
    #       - os: windows-latest
    #         target: win32-arm64
    #         npm_config_arch: arm64
    #       - os: ubuntu-latest
    #         target: linux-x64
    #         npm_config_arch: x64
    #       - os: ubuntu-latest
    #         target: linux-arm64
    #         npm_config_arch: arm64
    #       - os: ubuntu-latest
    #         target: linux-armhf
    #         npm_config_arch: arm
    #       - os: ubuntu-latest
    #         target: alpine-x64
    #         npm_config_arch: x64
    #       - os: ubuntu-latest
    #         target: alpine-arm64
    #         npm_config_arch: arm64
    #       - os: macos-latest
    #         target: darwin-x64
    #         npm_config_arch: x64
    #       - os: macos-latest
    #         target: darwin-arm64
    #         npm_config_arch: arm64
    #       - os: ubuntu-latest
    #         target: universal
    # runs-on: ${{ matrix.os }}  
    runs-on: ubuntu-latest

    # Even though semantic-release will not publish anything, it still needs to
    # validate the GITHUB_TOKEN
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # - if: matrix.target != 'universal'
      #   name: Install dependencies (with binaries)
      #   run: npm ci
      #   env:
      #     npm_config_arch: ${{ matrix.npm_config_arch }}
      # - if: matrix.target == 'universal'
      #   name: Install dependencies (without binaries)
      #   run: npm ci

      - name: Install Dependencies
        run: npm ci

      # - run: npx semantic-release --extends ./package.release.config.mjs
      #   env:
      #     VSCE_TARGET: ${{ matrix.target }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npx semantic-release --extends ./package.release.config.mjs
        env:
          VSCE_TARGET: 'universal'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: actions/upload-artifact@v5
      #   with:
      #     name: ${{ matrix.target }}
      #     path: "*.vsix"

      - uses: actions/upload-artifact@v5
        with:
          name: 'universal'
          path: "*.vsix"

      # vsce updates the version in package.json and package-lock.json during
      # package step, so we need to save them for the publish step
      # - if: matrix.target == 'universal'
      #   uses: actions/upload-artifact@v5
      #   with:
      #     name: package-json
      #     path: |
      #       package.json
      #       package-lock.json

      - uses: actions/upload-artifact@v5
        with:
          name: package-json
          path: |
            package.json
            package-lock.json

  release:
    if: github.event_name != 'schedule'

    # needs: [test, build]
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - uses: actions/checkout@v5
        # with:
        #   token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE || github.token }}
      - uses: actions/download-artifact@v6
        with:
          merge-multiple: true
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci
      - run: npm audit signatures
      # Only run on push events or pull requests coming from the same repository, except from dependabot
      - run: npx semantic-release --extends ./publish.release.config.mjs
        if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}