name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # This is to catch new releases of VS Code which could cause the extension to break
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read # for checkout

jobs:
  test:
    name: Run Tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests on Linux
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run Tests on Non-Linux
        run: npm test
        if: runner.os != 'Linux'

  build:
    name: Build and Package Extension
    # Not used as of now, but kept for future reference.
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [macos-latest, ubuntu-latest, windows-latest]    

    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest


    # Even though semantic-release will not publish anything, it still needs to
    # validate the GITHUB_TOKEN
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - run: npx semantic-release --extends ./package.release.config.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: actions/upload-artifact@v5
      #   with:
      #     name: ${{ matrix.target }}
      #     path: "*.vsix"

      - uses: actions/upload-artifact@v5
        with:
          name: 'universal'
          path: "*.vsix"

      # vsce updates the version in package.json and package-lock.json during
      # package step, so we need to save them for the publish step
      - uses: actions/upload-artifact@v5
        with:
          name: package-json
          path: |
            package.json
            package-lock.json

  release:
    if: github.event_name != 'schedule'
    name: Publish Release

    # needs: [test, build]
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - uses: actions/checkout@v5
        # with:
        #   token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE || github.token }}
      - uses: actions/download-artifact@v6
        with:
          merge-multiple: true
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci
      - run: npm audit signatures
      # Only run on push events or pull requests coming from the same repository, except from dependabot
      - run: npx semantic-release --extends ./publish.release.config.mjs
        if: github.event_name == 'push' || github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}